### ISSUE TITLE
another bug in Sf_t

### ISSUE THREAD

**Issue by alexlib** [MarkBaevsky/PTV_analysis_TNTI#6]
Temp=sqrt(Temp(:,1).^2+Temp(:,2).^2+Temp(:,3).^2); %Norm 

what is this line? the structure function shall be a scalar value but of a tangential to the trajectory or a transverse to it component.

**Comment by MarkBaevsky** [comment]
Velocity by itself is tangential to trajectory. And there is no transverse
component of velocity to trajectory. The line is a norm of velocity vector.

**Comment by alexlib** [comment]
Right. I wonder if it has to be the manitude of 1 minus the magnitude of 2 to power exp. in your case the third power looks like the second one. 

Alex Liberzon | Turbulence Structure Laboratory | Tel Aviv University | +972-3-640-8928 | http://www.eng.tau.ac.il/~alexlib

**Comment by alexlib** [comment]
I think we've seen another version - you changed in the lab this line
https://github.com/MarkBaevsky/PTV_analysis_TNTI/blob/master/SF_t.m#L74

to use scalar components of velocity along the trajectory. 

we saw the different second order which was not bad. I wonder about 3rd order. 

in addition, we need to check carefully how many points we have in each bin when we average - maybe this is one of the effects that the different number of bins masks the result.

**Comment by MarkBaevsky** [comment]
Here are the updated figures. I also committed the code. I will see how I
can plot the bins.

On 1 July 2015 at 09:09, Alex Liberzon <notifications@github.com> wrote:

> I think we've seen another version - you changed in the lab this line
> https://github.com/MarkBaevsky/PTV_analysis_TNTI/blob/master/SF_t.m#L74
>
> to use scalar components of velocity along the trajectory.
>
> we saw the different second order which was not bad. I wonder about 3rd
> order.
>
> in addition, we need to check carefully how many points we have in each
> bin when we average - maybe this is one of the effects that the different
> number of bins masks the result.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarkBaevsky/PTV_analysis_TNTI/issues/6#issuecomment-117444934>
> .
>



-- 
*Mark Baevsky - M.Sc. Student*
*Turbulence Structure Laboratory*
*School of Mechanical Engineering*
*Tel-Aviv University*
*Laboratory: +972-3-640-6860*

**Comment by MarkBaevsky** [comment]
Here I added the N plot, number of values used in the averaging for each
tau.

On 1 July 2015 at 09:48, Mark Baevsky <mark.me08@gmail.com> wrote:

> Here are the updated figures. I also committed the code. I will see how I
> can plot the bins.
>
> On 1 July 2015 at 09:09, Alex Liberzon <notifications@github.com> wrote:
>
>> I think we've seen another version - you changed in the lab this line
>> https://github.com/MarkBaevsky/PTV_analysis_TNTI/blob/master/SF_t.m#L74
>>
>> to use scalar components of velocity along the trajectory.
>>
>> we saw the different second order which was not bad. I wonder about 3rd
>> order.
>>
>> in addition, we need to check carefully how many points we have in each
>> bin when we average - maybe this is one of the effects that the different
>> number of bins masks the result.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MarkBaevsky/PTV_analysis_TNTI/issues/6#issuecomment-117444934>
>> .
>>
>
>
>
> --
> *Mark Baevsky - M.Sc. Student*
> *Turbulence Structure Laboratory*
> *School of Mechanical Engineering*
> *Tel-Aviv University*
> *Laboratory: +972-3-640-6860 <%2B972-3-640-6860>*
>



-- 
*Mark Baevsky - M.Sc. Student*
*Turbulence Structure Laboratory*
*School of Mechanical Engineering*
*Tel-Aviv University*
*Laboratory: +972-3-640-6860*

**Comment by alexlib** [comment]
no attachments. send to e-mail

**Comment by MarkBaevsky** [comment]
What?

On 1 July 2015 at 14:18, Alex Liberzon <notifications@github.com> wrote:

> no attachments. send to e-mail
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarkBaevsky/PTV_analysis_TNTI/issues/6#issuecomment-117614266>
> .
>



-- 
*Mark Baevsky - M.Sc. Student*
*Turbulence Structure Laboratory*
*School of Mechanical Engineering*
*Tel-Aviv University*
*Laboratory: +972-3-640-6860*
